# Generated by Django 6.1 on 2026-09-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_payment_id_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
