# Generated by Django 6.1 on 2026-09-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/product_placeholder.png', upload_to='images/'),
        ),
    ]
