from django.core.management.base import BaseCommand
from store.models import Product, Category


class Command(BaseCommand):
    help = "Create products"

    def handle(self, *args, **kwargs):

        products = [
            # Computers & Laptops
            {
                "name": "ASUS VivoBook 15",
                "description": "A versatile laptop suitable for everyday work, study and entertainment.",
                "price": 55000,
                "discounted_price": 49999,
                "stock": 20,
                "category": "Computers & Laptops",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Lenovo IdeaPad Slim 3",
                "description": "Slim and practical laptop designed for productivity and everyday computing.",
                "price": 52000,
                "discounted_price": 46999,
                "stock": 15,
                "category": "Computers & Laptops",
                "image": "images/laptop.jpg",
            },
            {
                "name": "HP 15s",
                "description": "Reliable everyday laptop for work, study and entertainment.",
                "price": 50000,
                "discounted_price": 44999,
                "stock": 18,
                "category": "Computers & Laptops",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Acer Aspire 5",
                "description": "Balanced laptop offering strong performance for everyday productivity.",
                "price": 58000,
                "discounted_price": 52999,
                "stock": 12,
                "category": "Computers & Laptops",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Dell Inspiron 15",
                "description": "Everyday laptop with a practical design for work and study.",
                "price": 60000,
                "discounted_price": 54999,
                "stock": 10,
                "category": "Computers & Laptops",
                "image": "images/laptop.jpg",
            },
            {
                "name": "ASUS TUF Gaming F15",
                "description": "Gaming laptop built for demanding games and performance-focused workloads.",
                "price": 85000,
                "discounted_price": 77999,
                "stock": 8,
                "category": "Computers & Laptops",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Lenovo LOQ Gaming Laptop",
                "description": "Performance gaming laptop designed for gaming and demanding applications.",
                "price": 90000,
                "discounted_price": 82999,
                "stock": 7,
                "category": "Computers & Laptops",
                "image": "images/laptop.jpg",
            },
            {
                "name": "HP Victus Gaming 15",
                "description": "Gaming laptop combining strong performance with a clean modern design.",
                "price": 80000,
                "discounted_price": 72999,
                "stock": 9,
                "category": "Computers & Laptops",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Acer Nitro V",
                "description": "Gaming-focused laptop designed for high-performance gaming and productivity.",
                "price": 82000,
                "discounted_price": 74999,
                "stock": 6,
                "category": "Computers & Laptops",
                "image": "images/laptop.jpg",
            },
            {
                "name": "MSI Modern 14",
                "description": "Compact laptop designed for productivity, study and everyday use.",
                "price": 55000,
                "discounted_price": 49999,
                "stock": 14,
                "category": "Computers & Laptops",
                "image": "images/laptop.jpg",
            },

            # Mobile Phones
            {
                "name": "Samsung Galaxy A55",
                "description": "Modern smartphone with a bright display and versatile camera system.",
                "price": 45000,
                "discounted_price": 39999,
                "stock": 20,
                "category": "Mobile Phones",
                "image": "images/laptop.jpg",
            },
            {
                "name": "OnePlus Nord 4",
                "description": "Powerful smartphone offering smooth performance and a premium design.",
                "price": 35000,
                "discounted_price": 31999,
                "stock": 18,
                "category": "Mobile Phones",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Google Pixel 8a",
                "description": "Compact smartphone with excellent photography and clean Android software.",
                "price": 52000,
                "discounted_price": 46999,
                "stock": 12,
                "category": "Mobile Phones",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Nothing Phone 2a",
                "description": "Stylish smartphone with a distinctive transparent-inspired design.",
                "price": 28000,
                "discounted_price": 24999,
                "stock": 20,
                "category": "Mobile Phones",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Xiaomi Redmi Note 14 Pro",
                "description": "Feature-rich smartphone offering strong performance and camera capabilities.",
                "price": 30000,
                "discounted_price": 26999,
                "stock": 16,
                "category": "Mobile Phones",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Motorola Edge 50 Fusion",
                "description": "Slim smartphone with smooth performance and a high-quality display.",
                "price": 32000,
                "discounted_price": 28999,
                "stock": 14,
                "category": "Mobile Phones",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Samsung Galaxy S24 FE",
                "description": "Premium smartphone experience with a powerful processor and versatile cameras.",
                "price": 65000,
                "discounted_price": 57999,
                "stock": 10,
                "category": "Mobile Phones",
                "image": "images/laptop.jpg",
            },
            {
                "name": "OnePlus 13R",
                "description": "High-performance smartphone designed for demanding users and gaming.",
                "price": 45000,
                "discounted_price": 41999,
                "stock": 11,
                "category": "Mobile Phones",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Realme GT 6",
                "description": "Performance-focused smartphone with a powerful processor and fast display.",
                "price": 42000,
                "discounted_price": 37999,
                "stock": 13,
                "category": "Mobile Phones",
                "image": "images/laptop.jpg",
            },
            {
                "name": "iQOO Neo 10",
                "description": "Gaming-oriented smartphone offering powerful performance and fast charging.",
                "price": 40000,
                "discounted_price": 35999,
                "stock": 15,
                "category": "Mobile Phones",
                "image": "images/laptop.jpg",
            },

            # Accessories
            {
                "name": "Logitech MX Master 3S",
                "description": "Premium wireless mouse designed for productivity and precision.",
                "price": 10000,
                "discounted_price": 8999,
                "stock": 20,
                "category": "Accessories",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Logitech K380 Keyboard",
                "description": "Compact wireless keyboard suitable for computers and mobile devices.",
                "price": 4000,
                "discounted_price": 3499,
                "stock": 25,
                "category": "Accessories",
                "image": "images/laptop.jpg",
            },
            {
                "name": "HP Wireless Keyboard & Mouse",
                "description": "Convenient wireless keyboard and mouse combination for everyday computing.",
                "price": 3000,
                "discounted_price": 2499,
                "stock": 30,
                "category": "Accessories",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Anker USB-C Hub",
                "description": "Multi-port USB-C hub for expanding laptop connectivity.",
                "price": 5000,
                "discounted_price": 4299,
                "stock": 18,
                "category": "Accessories",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Logitech C920 Webcam",
                "description": "Full HD webcam suitable for video calls, streaming and online meetings.",
                "price": 8000,
                "discounted_price": 6999,
                "stock": 15,
                "category": "Accessories",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Samsung 25W USB-C Charger",
                "description": "Compact fast charger designed for compatible USB-C devices.",
                "price": 2000,
                "discounted_price": 1599,
                "stock": 35,
                "category": "Accessories",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Anker PowerCore 20000mAh",
                "description": "High-capacity portable power bank for charging devices on the go.",
                "price": 4000,
                "discounted_price": 3499,
                "stock": 22,
                "category": "Accessories",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Portronics USB-C Cable",
                "description": "Durable USB-C cable suitable for charging and data transfer.",
                "price": 1000,
                "discounted_price": 699,
                "stock": 40,
                "category": "Accessories",
                "image": "images/laptop.jpg",
            },
            {
                "name": "TP-Link Wi-Fi 6 Router",
                "description": "Modern wireless router providing fast and reliable home connectivity.",
                "price": 5000,
                "discounted_price": 4499,
                "stock": 15,
                "category": "Accessories",
                "image": "images/laptop.jpg",
            },
            {
                "name": "AmazonBasics Laptop Stand",
                "description": "Adjustable laptop stand designed for a more comfortable working position.",
                "price": 2500,
                "discounted_price": 1999,
                "stock": 20,
                "category": "Accessories",
                "image": "images/laptop.jpg",
            },

            # Audio
            {
                "name": "Sony WH-1000XM5",
                "description": "Premium wireless headphones with advanced noise cancellation.",
                "price": 35000,
                "discounted_price": 29999,
                "stock": 10,
                "category": "Audio",
                "image": "images/laptop.jpg",
            },
            {
                "name": "JBL Tune 770NC",
                "description": "Wireless headphones with active noise cancellation and long battery life.",
                "price": 10000,
                "discounted_price": 8499,
                "stock": 18,
                "category": "Audio",
                "image": "images/laptop.jpg",
            },
            {
                "name": "boAt Rockerz 450",
                "description": "Affordable wireless headphones designed for everyday entertainment.",
                "price": 2500,
                "discounted_price": 1999,
                "stock": 30,
                "category": "Audio",
                "image": "images/laptop.jpg",
            },
            {
                "name": "OnePlus Buds 3",
                "description": "Wireless earbuds delivering balanced sound and convenient controls.",
                "price": 6000,
                "discounted_price": 4999,
                "stock": 20,
                "category": "Audio",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Nothing Ear",
                "description": "Stylish wireless earbuds with a distinctive design and strong audio performance.",
                "price": 9000,
                "discounted_price": 7999,
                "stock": 15,
                "category": "Audio",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Sony WF-C700N",
                "description": "Compact wireless earbuds with noise cancellation and comfortable fit.",
                "price": 10000,
                "discounted_price": 8499,
                "stock": 14,
                "category": "Audio",
                "image": "images/laptop.jpg",
            },
            {
                "name": "JBL Flip 6",
                "description": "Portable Bluetooth speaker designed for powerful sound outdoors and indoors.",
                "price": 12000,
                "discounted_price": 9999,
                "stock": 12,
                "category": "Audio",
                "image": "images/laptop.jpg",
            },
            {
                "name": "boAt Stone 620",
                "description": "Portable Bluetooth speaker with a rugged design and wireless connectivity.",
                "price": 4000,
                "discounted_price": 3299,
                "stock": 20,
                "category": "Audio",
                "image": "images/laptop.jpg",
            },

            # Gaming
            {
                "name": "Logitech G502 Hero",
                "description": "High-performance gaming mouse with programmable controls.",
                "price": 6000,
                "discounted_price": 4999,
                "stock": 15,
                "category": "Gaming",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Razer DeathAdder V2",
                "description": "Ergonomic gaming mouse designed for accurate and responsive gameplay.",
                "price": 5000,
                "discounted_price": 3999,
                "stock": 18,
                "category": "Gaming",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Redragon K552 Mechanical Keyboard",
                "description": "Compact mechanical gaming keyboard with responsive switches.",
                "price": 4000,
                "discounted_price": 3299,
                "stock": 20,
                "category": "Gaming",
                "image": "images/laptop.jpg",
            },
            {
                "name": "HyperX Alloy Origins",
                "description": "Premium mechanical gaming keyboard built for competitive gaming.",
                "price": 10000,
                "discounted_price": 8499,
                "stock": 12,
                "category": "Gaming",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Logitech G435 Gaming Headset",
                "description": "Lightweight wireless gaming headset designed for comfortable long sessions.",
                "price": 8000,
                "discounted_price": 6999,
                "stock": 15,
                "category": "Gaming",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Xbox Wireless Controller",
                "description": "Wireless controller suitable for gaming on Xbox and compatible devices.",
                "price": 6000,
                "discounted_price": 5499,
                "stock": 14,
                "category": "Gaming",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Cosmic Byte Gaming Mouse Pad",
                "description": "Large gaming mouse pad providing a smooth tracking surface.",
                "price": 1500,
                "discounted_price": 999,
                "stock": 25,
                "category": "Gaming",
                "image": "images/laptop.jpg",
            },
            {
                "name": "ASUS TUF Gaming Monitor 24",
                "description": "Gaming monitor designed for smooth gameplay and responsive performance.",
                "price": 18000,
                "discounted_price": 15999,
                "stock": 8,
                "category": "Gaming",
                "image": "images/laptop.jpg",
            },

            # Wearables
            {
                "name": "Samsung Galaxy Watch 7",
                "description": "Smartwatch with fitness tracking, notifications and smart features.",
                "price": 35000,
                "discounted_price": 29999,
                "stock": 10,
                "category": "Wearables",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Apple Watch SE",
                "description": "Smartwatch offering health, fitness and connectivity features.",
                "price": 30000,
                "discounted_price": 26999,
                "stock": 12,
                "category": "Wearables",
                "image": "images/laptop.jpg",
            },
            {
                "name": "OnePlus Watch 2",
                "description": "Premium smartwatch with fitness tracking and smart connectivity features.",
                "price": 25000,
                "discounted_price": 21999,
                "stock": 10,
                "category": "Wearables",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Amazfit Active",
                "description": "Lightweight smartwatch focused on fitness tracking and everyday health monitoring.",
                "price": 15000,
                "discounted_price": 12999,
                "stock": 16,
                "category": "Wearables",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Redmi Watch 5",
                "description": "Affordable smartwatch with a large display and fitness features.",
                "price": 7000,
                "discounted_price": 5999,
                "stock": 20,
                "category": "Wearables",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Noise ColorFit Pro",
                "description": "Smartwatch designed for fitness tracking and everyday notifications.",
                "price": 5000,
                "discounted_price": 3999,
                "stock": 25,
                "category": "Wearables",
                "image": "images/laptop.jpg",
            },
            {
                "name": "boAt Ultima Chronos",
                "description": "Feature-packed smartwatch with fitness and smart notification features.",
                "price": 6000,
                "discounted_price": 4999,
                "stock": 20,
                "category": "Wearables",
                "image": "images/laptop.jpg",
            },

            # Home Appliances
            {
                "name": "Philips Air Fryer",
                "description": "Convenient air fryer designed for quick and healthier cooking.",
                "price": 10000,
                "discounted_price": 8499,
                "stock": 12,
                "category": "Home Appliances",
                "image": "images/laptop.jpg",
            },
            {
                "name": "LG 1.5 Ton Split AC",
                "description": "Energy-efficient split air conditioner designed for comfortable home cooling.",
                "price": 45000,
                "discounted_price": 39999,
                "stock": 6,
                "category": "Home Appliances",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Samsung 253L Refrigerator",
                "description": "Spacious refrigerator designed for efficient everyday food storage.",
                "price": 35000,
                "discounted_price": 31999,
                "stock": 7,
                "category": "Home Appliances",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Philips Mixer Grinder",
                "description": "Powerful kitchen appliance suitable for mixing and grinding ingredients.",
                "price": 6000,
                "discounted_price": 4999,
                "stock": 15,
                "category": "Home Appliances",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Xiaomi Smart Air Purifier",
                "description": "Smart air purifier designed to improve indoor air quality.",
                "price": 15000,
                "discounted_price": 12999,
                "stock": 10,
                "category": "Home Appliances",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Bajaj Electric Kettle",
                "description": "Compact electric kettle for quickly boiling water.",
                "price": 2500,
                "discounted_price": 1999,
                "stock": 25,
                "category": "Home Appliances",
                "image": "images/laptop.jpg",
            },
            {
                "name": "Philips Steam Iron",
                "description": "Steam iron designed for convenient and efficient clothes ironing.",
                "price": 3000,
                "discounted_price": 2499,
                "stock": 20,
                "category": "Home Appliances",
                "image": "images/laptop.jpg",
            },
        ]

        for item in products:
            category = Category.objects.get(name=item["category"])

            Product.objects.create(
                name=item["name"],
                description=item["description"],
                price=item["price"],
                discounted_price=item["discounted_price"],
                stock=item["stock"],
                category=category,
                image=item["image"],
            )

        self.stdout.write(
            self.style.SUCCESS(
                f"{len(products)} products created successfully."
            )
        )